alter table effect_to_item drop foreign key FKo9h4og97snqne2dufuluj5a6c;
alter table effect_to_item drop foreign key FKg2e4kh6n5hng2q5mie4bdsk2f;
alter table effect_to_skill drop foreign key FK3a35n0c2jbw3btqpcxascfru;
alter table effect_to_skill drop foreign key FK6xm795kot6fxfgd6xxvc8frec;
alter table effect_to_unit drop foreign key FKlfyy72mayqghmbmbq3und5srk;
alter table effect_to_unit drop foreign key FK4r35oobve7u1tjmvwa05akdjk;
alter table EquippedItem drop foreign key FKb3g0grjarvt8rj9p0xonmljye;
alter table EquippedItem drop foreign key FK7bsavvglgq5urwsc1cbaue063;
alter table EquippedItem drop foreign key FKq7cgsnnf2uk1ykt45cmypj0ql;
alter table GameCharacter drop foreign key FKhq2c9rudweouqltgaudim1pu4;
alter table Inventory drop foreign key FKdk0uesqhppuvu5bn1rei3rc2m;
alter table Inventory drop foreign key FK64fmfsftamktm4cu2h1e06n31;
alter table Item_Slot drop foreign key FKny0vx5jrht1wo4geqo4den4t9;
alter table Item_Slot drop foreign key FK88ek70jkk4e0jkbtca21i38g9;
alter table item_to_location drop foreign key FKfml1ipw7pqofehr0dl6d5murm;
alter table item_to_location drop foreign key FKdfwprg45dusud8tlxu10bo56b;
alter table item_to_slot drop foreign key FKgf2otxswholu2kue6kb1p9psy;
alter table item_to_slot drop foreign key FK1ryn0um1vu4p7qxr8bwft94am;
alter table obstacle_to_location drop foreign key FKlt69h91j55lu0xa2ltuqsqdv8;
alter table obstacle_to_location drop foreign key FKg79yb6v85wv3nmgf14joalujs;
alter table obstacle_to_location drop foreign key FKgdqgesqsgqxq61emj4mdg7qxq;
alter table Player drop foreign key FKp52fxyehm4mnfvpipmr85df7w;
alter table Player_GameCharacter drop foreign key FKkbtt18kcbcejsdm7x9xekjh9a;
alter table Player_GameCharacter drop foreign key FK2j6a16pyo2uo7nb674s1ad0rw;
alter table Profile drop foreign key FKgi6cead8tmauko9ak4lpf9a3;
alter table Race_Skill drop foreign key FKbvarc4h5moh0j5lfj4tcdcpmk;
alter table Race_Skill drop foreign key FKb0ibe888d2niq7ddh6u4qief0;
alter table skill_to_class drop foreign key FKlhdd2e9acl0lt5i2mx45maoyc;
alter table skill_to_class drop foreign key FKllgh33exes24trt2l99j1wxad;
alter table unit drop foreign key FK995tu7r73bod7vqc32kj3xa31;
alter table unit drop foreign key FKfk5kekrrj158m0w4w0byqr2mw;
alter table unit_to_skill drop foreign key FKctryx0g2u7h3yrgn5o2mo3pe5;
alter table unit_to_skill drop foreign key FKi7jgusrqpbfor7eibwcfu0rif;
drop table if exists Class;
drop table if exists Effect;
drop table if exists effect_to_item;
drop table if exists effect_to_skill;
drop table if exists effect_to_unit;
drop table if exists EquippedItem;
drop table if exists GameCharacter;
drop table if exists hibernate_sequence;
drop table if exists Inventory;
drop table if exists Item;
drop table if exists Item_Slot;
drop table if exists item_to_location;
drop table if exists item_to_slot;
drop table if exists Location;
drop table if exists Map;
drop table if exists Mob;
drop table if exists Obstacle;
drop table if exists obstacle_to_location;
drop table if exists Player;
drop table if exists Player_GameCharacter;
drop table if exists Profile;
drop table if exists Race;
drop table if exists Race_Skill;
drop table if exists Skill;
drop table if exists skill_to_class;
drop table if exists Slot;
drop table if exists unit;
drop table if exists unit_to_skill;
create table Class (id integer not null auto_increment, agiMultiplier double precision not null, intMultiplier double precision not null, name varchar(255), staMultiplier double precision not null, strMultiplier double precision not null, primary key (id)) engine=InnoDB;
create table Effect (id integer not null auto_increment, amount integer not null, effectType integer, magicalEffect bit not null, name varchar(255), target integer, primary key (id)) engine=InnoDB;
create table effect_to_item (item_id integer not null, effect_id integer not null, primary key (item_id, effect_id)) engine=InnoDB;
create table effect_to_skill (description varchar(255), duration integer not null, skill_id integer not null, effect_id integer not null, primary key (skill_id, effect_id)) engine=InnoDB;
create table effect_to_unit (unit_id integer not null, effect_id integer not null, primary key (unit_id, effect_id)) engine=InnoDB;
create table EquippedItem (id integer not null auto_increment, gearSlot_id integer, item_id integer, unit_id integer, primary key (id)) engine=InnoDB;
create table GameCharacter (id integer not null auto_increment, name varchar(255), unit_id integer, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table Inventory (id integer not null auto_increment, item_id integer, unit_id integer, primary key (id)) engine=InnoDB;
create table Item (id integer not null auto_increment, parentId integer not null, primary key (id)) engine=InnoDB;
create table Item_Slot (Item_id integer not null, possibleSlots_id integer not null, primary key (Item_id, possibleSlots_id)) engine=InnoDB;
create table item_to_location (location_id integer not null, item_id integer not null, primary key (location_id, item_id)) engine=InnoDB;
create table item_to_slot (slot_id integer not null, item_id integer not null, primary key (slot_id, item_id)) engine=InnoDB;
create table Location (id integer not null auto_increment, obstacleId integer not null, primary key (id)) engine=InnoDB;
create table Map (id integer not null auto_increment, parentId integer not null, primary key (id)) engine=InnoDB;
create table Mob (id integer not null auto_increment, name varchar(255), parentId integer not null, patrolRange integer not null, serverId integer not null, templateId integer not null, unitId integer not null, primary key (id)) engine=InnoDB;
create table Obstacle (id integer not null auto_increment, type varchar(255), primary key (id)) engine=InnoDB;
create table obstacle_to_location (map_id integer not null, location_id integer not null, obstacle_id integer not null, primary key (obstacle_id, location_id)) engine=InnoDB;
create table Player (id integer not null auto_increment, login varchar(255), password varchar(255), profile_id integer, primary key (id)) engine=InnoDB;
create table Player_GameCharacter (Player_id integer not null, gameCharacter_id integer not null, primary key (Player_id, gameCharacter_id)) engine=InnoDB;
create table Profile (id integer not null auto_increment, email varchar(255), fname varchar(255), lname varchar(255), player_id integer, primary key (id)) engine=InnoDB;
create table Race (id integer not null auto_increment, agility integer not null, intellect integer not null, name varchar(255), stamina integer not null, strength integer not null, primary key (id)) engine=InnoDB;
create table Race_Skill (Race_id integer not null, raceSkills_id integer not null, primary key (Race_id, raceSkills_id)) engine=InnoDB;
create table Skill (id integer not null auto_increment, level integer not null, name varchar(255), primary key (id)) engine=InnoDB;
create table skill_to_class (id integer not null, level integer not null, _class_id integer, skill_id integer, primary key (id)) engine=InnoDB;
create table Slot (id integer not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table unit (id integer not null auto_increment, currentHp integer not null, currentMana integer not null, exp bigint not null, _class_id integer, race_id integer, primary key (id)) engine=InnoDB;
create table unit_to_skill (unit_id integer not null, skill_id integer not null, primary key (unit_id, skill_id)) engine=InnoDB;
alter table Class add constraint UK_q2aas4sujsrmis3we0unjtgq2 unique (name);
alter table Effect add constraint UK_77djs4akidwal0oeai9m7hni2 unique (name);
alter table Item_Slot add constraint UK_cey1paih0oi8lxbuowqykku unique (possibleSlots_id);
alter table Player add constraint UK_9pa34bx2tfj3o34jukylgs8nx unique (login);
alter table Player_GameCharacter add constraint UK_tpr8h39cj0tptk15sat9ijf59 unique (gameCharacter_id);
alter table Profile add constraint UK_e521n65fpj809whmjdr1s1sdb unique (email);
alter table Race add constraint UK_9q2rghe8klp45i37fjpi5selj unique (name);
alter table Slot add constraint UK_ab3493adhr9mwi4g07t1ijhnd unique (name);
alter table effect_to_item add constraint FKo9h4og97snqne2dufuluj5a6c foreign key (item_id) references Item (id);
alter table effect_to_item add constraint FKg2e4kh6n5hng2q5mie4bdsk2f foreign key (effect_id) references Effect (id);
alter table effect_to_skill add constraint FK3a35n0c2jbw3btqpcxascfru foreign key (skill_id) references Skill (id);
alter table effect_to_skill add constraint FK6xm795kot6fxfgd6xxvc8frec foreign key (effect_id) references Effect (id);
alter table effect_to_unit add constraint FKlfyy72mayqghmbmbq3und5srk foreign key (unit_id) references unit (id);
alter table effect_to_unit add constraint FK4r35oobve7u1tjmvwa05akdjk foreign key (effect_id) references Effect (id);
alter table EquippedItem add constraint FKb3g0grjarvt8rj9p0xonmljye foreign key (gearSlot_id) references Slot (id);
alter table EquippedItem add constraint FK7bsavvglgq5urwsc1cbaue063 foreign key (item_id) references Item (id);
alter table EquippedItem add constraint FKq7cgsnnf2uk1ykt45cmypj0ql foreign key (unit_id) references unit (id);
alter table GameCharacter add constraint FKhq2c9rudweouqltgaudim1pu4 foreign key (unit_id) references unit (id);
alter table Inventory add constraint FKdk0uesqhppuvu5bn1rei3rc2m foreign key (item_id) references Item (id);
alter table Inventory add constraint FK64fmfsftamktm4cu2h1e06n31 foreign key (unit_id) references unit (id);
alter table Item_Slot add constraint FKny0vx5jrht1wo4geqo4den4t9 foreign key (possibleSlots_id) references Slot (id);
alter table Item_Slot add constraint FK88ek70jkk4e0jkbtca21i38g9 foreign key (Item_id) references Item (id);
alter table item_to_location add constraint FKfml1ipw7pqofehr0dl6d5murm foreign key (location_id) references Location (id);
alter table item_to_location add constraint FKdfwprg45dusud8tlxu10bo56b foreign key (item_id) references Item (id);
alter table item_to_slot add constraint FKgf2otxswholu2kue6kb1p9psy foreign key (slot_id) references Slot (id);
alter table item_to_slot add constraint FK1ryn0um1vu4p7qxr8bwft94am foreign key (item_id) references Item (id);
alter table obstacle_to_location add constraint FKlt69h91j55lu0xa2ltuqsqdv8 foreign key (map_id) references Map (id);
alter table obstacle_to_location add constraint FKg79yb6v85wv3nmgf14joalujs foreign key (location_id) references Location (id);
alter table obstacle_to_location add constraint FKgdqgesqsgqxq61emj4mdg7qxq foreign key (obstacle_id) references Obstacle (id);
alter table Player add constraint FKp52fxyehm4mnfvpipmr85df7w foreign key (profile_id) references Profile (id);
alter table Player_GameCharacter add constraint FKkbtt18kcbcejsdm7x9xekjh9a foreign key (gameCharacter_id) references GameCharacter (id);
alter table Player_GameCharacter add constraint FK2j6a16pyo2uo7nb674s1ad0rw foreign key (Player_id) references Player (id);
alter table Profile add constraint FKgi6cead8tmauko9ak4lpf9a3 foreign key (player_id) references Player (id);
alter table Race_Skill add constraint FKbvarc4h5moh0j5lfj4tcdcpmk foreign key (raceSkills_id) references Skill (id);
alter table Race_Skill add constraint FKb0ibe888d2niq7ddh6u4qief0 foreign key (Race_id) references Race (id);
alter table skill_to_class add constraint FKlhdd2e9acl0lt5i2mx45maoyc foreign key (_class_id) references Class (id);
alter table skill_to_class add constraint FKllgh33exes24trt2l99j1wxad foreign key (skill_id) references Skill (id);
alter table unit add constraint FK995tu7r73bod7vqc32kj3xa31 foreign key (_class_id) references Class (id);
alter table unit add constraint FKfk5kekrrj158m0w4w0byqr2mw foreign key (race_id) references Race (id);
alter table unit_to_skill add constraint FKctryx0g2u7h3yrgn5o2mo3pe5 foreign key (unit_id) references unit (id);
alter table unit_to_skill add constraint FKi7jgusrqpbfor7eibwcfu0rif foreign key (skill_id) references Skill (id);
