create table Class (id integer not null, agiMultiplier double precision not null, agility integer not null, intMultiplier double precision not null, intellect integer not null, name varchar(255), staMultiplier double precision not null, stamina integer not null, strMultiplier double precision not null, strength integer not null, primary key (id)) engine=InnoDB;
create table Effect (id integer not null, name varchar(255), primary key (id)) engine=InnoDB;
create table effect_to_item (effectId integer not null, itemId integer not null, primary key (effectId, itemId)) engine=InnoDB;
create table effect_to_skill (effectId integer not null, skillId integer not null, primary key (effectId, skillId)) engine=InnoDB;
create table effect_to_unit (effectId integer not null, unitId integer not null, primary key (effectId, unitId)) engine=InnoDB;
create table EquippedItem (id integer not null, gearSlot_id integer, itemId integer, unitId integer, primary key (id)) engine=InnoDB;
create table gameCharacter (id integer not null, name varchar(255), unit_id integer, primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
create table Inventory (id integer not null, itemId integer not null, unitId integer not null, primary key (id)) engine=InnoDB;
create table Item (id integer not null, parentId integer not null, primary key (id)) engine=InnoDB;
create table Item_Slot (Item_id integer not null, possibleSlots_id integer not null, primary key (Item_id, possibleSlots_id)) engine=InnoDB;
create table item_to_location (itemId integer not null, locationId integer not null, primary key (itemId, locationId)) engine=InnoDB;
create table item_to_slot (itemId integer not null, slotId integer not null, primary key (itemId, slotId)) engine=InnoDB;
create table Location (id integer not null, obstacleId integer not null, primary key (id)) engine=InnoDB;
create table Map (id integer not null, parentId integer not null, primary key (id)) engine=InnoDB;
create table Mob (id integer not null, name varchar(255), parentId integer not null, patrolRange integer not null, serverId integer not null, templateId integer not null, unitId integer not null, primary key (id)) engine=InnoDB;
create table Obstacle (id integer not null, type varchar(255), primary key (id)) engine=InnoDB;
create table obstacle_to_location (locationId integer not null, mapId integer not null, obstacleId integer not null, map_id integer, primary key (locationId, obstacleId)) engine=InnoDB;
create table Player (id integer not null, login varchar(255), password varchar(255), primary key (id)) engine=InnoDB;
create table Player_gameCharacter (Player_id integer not null, gameCharacter_id integer not null, primary key (Player_id, gameCharacter_id)) engine=InnoDB;
create table Profile (id integer not null, email varchar(255), fname varchar(255), lname varchar(255), primary key (id)) engine=InnoDB;
create table Race (id integer not null, agiMultiplier double precision not null, intMultiplier double precision not null, name varchar(255), staMultiplier double precision not null, strMultiplier double precision not null, primary key (id)) engine=InnoDB;
create table Race_Skill (Race_id integer not null, raceSkills_id integer not null, primary key (Race_id, raceSkills_id)) engine=InnoDB;
create table Skill (id integer not null, level integer not null, name varchar(255), primary key (id)) engine=InnoDB;
create table skill_to_class (id integer not null, level integer not null, classId integer, skillId integer, primary key (id)) engine=InnoDB;
create table Slot (id integer not null, name varchar(255), primary key (id)) engine=InnoDB;
create table Unit (id integer not null, classId integer not null, currentHp integer not null, currentMana integer not null, exp bigint not null, raceId integer not null, template integer not null, primary key (id)) engine=InnoDB;
create table unit_to_skill (skillId integer not null, unitId integer not null, primary key (skillId, unitId)) engine=InnoDB;
alter table Item_Slot add constraint UK_cey1paih0oi8lxbuowqykku unique (possibleSlots_id);
alter table Player_gameCharacter add constraint UK_kka9xevi7am7fpgwk1ui3ildg unique (gameCharacter_id);
alter table effect_to_item add constraint FKm3k040enxds9u515rkxddpi7r foreign key (effectId) references Effect (id);
alter table effect_to_item add constraint FKhuuvm7lmqf97ldb2kit9d393x foreign key (itemId) references Item (id);
alter table effect_to_skill add constraint FK65gmmxq9ohh3iqmt7pnhvbxen foreign key (effectId) references Effect (id);
alter table effect_to_skill add constraint FK9lds0hsiks6no851vh4k5ejoe foreign key (skillId) references Skill (id);
alter table effect_to_unit add constraint FKeivf3ub2mltx73vgu7ixmhtv2 foreign key (effectId) references Effect (id);
alter table effect_to_unit add constraint FKh5ejvic6aaaasumcg68jebjc7 foreign key (unitId) references Unit (id);
alter table EquippedItem add constraint FKb3g0grjarvt8rj9p0xonmljye foreign key (gearSlot_id) references Slot (id);
alter table EquippedItem add constraint FK76m7426h4janil9pis7x5fc63 foreign key (itemId) references Item (id);
alter table EquippedItem add constraint FK63dspcw7qgy072bu8j4qo68q2 foreign key (unitId) references Unit (id);
alter table gameCharacter add constraint FKlp2jbb9berwl1u048rdysjpim foreign key (unit_id) references Unit (id);
alter table Item_Slot add constraint FKny0vx5jrht1wo4geqo4den4t9 foreign key (possibleSlots_id) references Slot (id);
alter table Item_Slot add constraint FK88ek70jkk4e0jkbtca21i38g9 foreign key (Item_id) references Item (id);
alter table item_to_location add constraint FKpt3740oj3treym8q1kf1hd5bg foreign key (itemId) references Item (id);
alter table item_to_location add constraint FK9aner1l9yt0npmfhksbj82yf3 foreign key (locationId) references Location (id);
alter table item_to_slot add constraint FKlhbhmktvt5jtug97u2t6it5kl foreign key (itemId) references Item (id);
alter table item_to_slot add constraint FKjjottb63acap39nta4a4morrs foreign key (slotId) references Slot (id);
alter table obstacle_to_location add constraint FKo0ymc4g1wo2ke81n8tpdq75d9 foreign key (locationId) references Location (id);
alter table obstacle_to_location add constraint FKlt69h91j55lu0xa2ltuqsqdv8 foreign key (map_id) references Map (id);
alter table obstacle_to_location add constraint FKt52xos7v9fnhd8k8nlnob5rai foreign key (obstacleId) references Obstacle (id);
alter table Player_gameCharacter add constraint FKouo4k3aumnjvaucsow9tkhqko foreign key (gameCharacter_id) references gameCharacter (id);
alter table Player_gameCharacter add constraint FK4i1cgb135w2rgu8rid78uws6q foreign key (Player_id) references Player (id);
alter table Race_Skill add constraint FKbvarc4h5moh0j5lfj4tcdcpmk foreign key (raceSkills_id) references Skill (id);
alter table Race_Skill add constraint FKb0ibe888d2niq7ddh6u4qief0 foreign key (Race_id) references Race (id);
alter table skill_to_class add constraint FKj37sy7tnl3nh613uj4hpudrje foreign key (classId) references Class (id);
alter table skill_to_class add constraint FK1bbo4nbws2rsmv3gof2ois57f foreign key (skillId) references Skill (id);
alter table unit_to_skill add constraint FKmsgofmiqg2p8g4q65o02yapss foreign key (skillId) references Skill (id);
alter table unit_to_skill add constraint FKm22rrkcnnu213t4c75i8nshpf foreign key (unitId) references Unit (id);
